id: P008192
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD181197
  title: སྦས་ཞབས་བྲག་དཀར་གྱི་གནས་ཡིག་དཀར་ཆག་འབྲིང་པོ་ཤིན་ཏུ་གསང་བ།
  author: ''
  volumes:
    3bbed9d52adc4f53817358a5305e449d:
      image_group_id: I1KG16383
      title: ''
      volume_number: 1
      total_pages: 64
      base_file: v001.txt
