id: I438460CB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:34:21+00:00'
last_modified: '2022-06-09T05:08:26.551323+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181197
  title: སྦས་ཞབས་བྲག་དཀར་གྱི་གནས་ཡིག་དཀར་ཆག་འབྲིང་པོ་ཤིན་ཏུ་གསང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B933:
      image_group_id: I1KG16383
      title: ''
      total_pages: 64
      order: 1
      base_file: B933.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
